"""Training data for the Architect's own neural tool classifier.

Groups the architect's 125 tools into intent clusters so only the relevant
subset gets injected into the LLM prompt per user message.

Each sample: (user_message, correct_tool_group)

Target: 40+ diverse samples per group for 95%+ classifier accuracy.
Includes typos, short commands, pronoun refs, and edge cases.

Tool groups (14 clusters + none):
  build       — create/build/modify/delete agents, check tools, classify, repo-to-agent
  run         — execute/stop/cancel/approve sessions, emergency stop
  schedule    — create/list/update/delete schedules, triggers, webhooks
  inspect     — view agents, sessions, steps, metrics, providers, versions
  memory      — user memory, agent memory, RAG, insights, knowledge
  plan        — TODO tasks, brainstorm, workspace plan
  delegate    — delegate to other agents, multi-agent workflows
  workspace   — workspace name, databases, credits, integrations, time
  teams       — team management, members, workflows, NFTs, rentals
  marketplace — publish/unpublish agents, marketplace listings, APIs
  federation  — federated agents, cross-node tasks, heartbeat
  governance  — compliance, audit trail, governance evaluation
  learning    — patterns, recommendations, feedback, classifier
  advanced    — anomaly detection, templates, limits, direct tool execution
"""
from typing import List, Tuple

TrainingSample = Tuple[str, str]


def get_training_data() -> List[TrainingSample]:
    samples: List[TrainingSample] = []

    # ── BUILD: create/modify/delete agents, tool selection, prompts ──
    _b = "build"
    samples += [
        # Create
        ("create an agent that scrapes YCombinator", _b),
        ("build me a web scraper agent", _b),
        ("make an agent to monitor stock prices", _b),
        ("create a research agent for AI news", _b),
        ("build an email agent that sends daily digests", _b),
        ("I need a new agent for social media monitoring", _b),
        ("set up an agent to track competitors", _b),
        ("create an automation agent for lead generation", _b),
        ("build an agent for data analysis", _b),
        ("create a code review agent", _b),
        ("make a content writing agent", _b),
        ("set up an agent to post on twitter", _b),
        ("I want to create an agent", _b),
        ("new agent please", _b),
        ("create a new agent", _b),
        ("build a market research agent", _b),
        ("make me a crypto price tracker agent", _b),
        ("I need an agent that monitors RSS feeds", _b),
        ("build an agent to analyze sentiment", _b),
        ("create a newsletter agent", _b),
        ("make an agent for SEO monitoring", _b),
        ("build a customer support agent", _b),
        ("I want an agent that generates reports", _b),
        ("create a data scraping agent", _b),
        # Modify
        ("modify my scraper agent to add email tool", _b),
        ("add web_search tool to my research agent", _b),
        ("remove the email tool from that agent", _b),
        ("change my agent's model to GPT-4o", _b),
        ("update the temperature to 0.3", _b),
        ("update my agent's system prompt", _b),
        ("change the instructions for my research agent", _b),
        ("rewrite the prompt to be more detailed", _b),
        ("refine agent instructions", _b),
        ("improve my agent's prompt", _b),
        ("make the agent better at scraping", _b),
        ("optimize my agent", _b),
        ("add the web search tool", _b),
        ("remove google sheets from that agent", _b),
        ("switch the model to claude", _b),
        ("change it to use groq", _b),
        ("give it more tools", _b),
        ("update agent config", _b),
        ("tweak the prompt", _b),
        ("edit agent instructions", _b),
        # Delete
        ("delete that agent", _b),
        ("delete the Market Research agent", _b),
        ("remove that agent", _b),
        ("delete it", _b),
        ("delete the 3 duplicates", _b),
        ("just delete them", _b),
        ("delete all three", _b),
        ("remove the duplicate agents", _b),
        ("delete the old agent", _b),
        ("get rid of that agent", _b),
        ("delete my scraper agent", _b),
        ("remove the broken agent", _b),
        ("kill that agent", _b),
        ("delete agents that are useless", _b),
        ("clean up duplicate agents", _b),
        ("delete the 3d one", _b),
        ("okay delate the 3d one", _b),
        ("just delete the 3 duplicates", _b),
        ("delete the last one too", _b),
        ("can you delete the remaining one", _b),
        ("remove all the market research ones", _b),
        ("delete all agents", _b),
        ("clear all my agents", _b),
        ("wipe all agents", _b),
        # Tools
        ("what tools should this agent have", _b),
        ("which tools are available for agents", _b),
        ("list all platform tools", _b),
        ("what tools can I give my agent", _b),
        ("show me available tools", _b),
        ("what tools exist", _b),
        ("check what integrations are connected", _b),
        # Google / Email tools
        ("connect google sheets to my agent", _b),
        ("add google sheets tool", _b),
        ("make an agent that reads my spreadsheet", _b),
        ("build an agent to update my google sheet", _b),
        ("create an agent that sends emails", _b),
        ("add email tool to my agent", _b),
        ("I want my agent to send gmail", _b),
        ("connect gmail to my agent", _b),
        ("make an agent that creates google docs", _b),
        ("add google docs tool", _b),
        ("build an agent to write documents", _b),
        ("set up an agent for spreadsheet automation", _b),
        ("create an agent that reads and writes sheets", _b),
        # Repo to agent
        ("convert this github repo to an agent", _b),
        ("analyze this repository", _b),
        ("turn my github project into an agent", _b),
        ("import agent from repo", _b),
        ("make an agent from this repo", _b),
        # Model / provider
        ("what models can I use", _b),
        ("list providers for building", _b),
        ("check if openai is available", _b),
        ("which LLMs work best for agents", _b),
        # Confirm / follow-up
        ("yes build it", _b),
        ("go ahead and create it", _b),
        ("yes, delete them", _b),
        ("confirm delete", _b),
        ("yes remove them all", _b),
        ("do it", _b),
        ("proceed with the build", _b),
        ("sounds good, build it", _b),
        ("yes make it", _b),
    ]

    # ── RUN: execute, stop, cancel, approve, emergency ──
    _r = "run"
    samples += [
        ("run my scraper agent", _r),
        ("execute the research agent now", _r),
        ("start my agent", _r),
        ("run it", _r),
        ("execute the agent", _r),
        ("fire it up", _r),
        ("launch the agent", _r),
        ("kick off the agent", _r),
        ("go run it now", _r),
        ("run the agent with a different goal", _r),
        ("start a new session for my agent", _r),
        ("try running it again", _r),
        ("run the market research agent", _r),
        ("execute my newsletter agent", _r),
        ("start the scraper", _r),
        ("run all agents", _r),
        ("run the first one", _r),
        ("execute it now", _r),
        ("start it up", _r),
        ("can you run that agent", _r),
        ("run it with goal: find AI news", _r),
        ("test run the agent", _r),
        # Stop / cancel
        ("stop my agent", _r),
        ("cancel the running session", _r),
        ("stop all running agents", _r),
        ("cancel that session", _r),
        ("halt the agent immediately", _r),
        ("abort the current run", _r),
        ("stop it", _r),
        ("cancel it", _r),
        ("kill the running session", _r),
        ("stop the execution", _r),
        # Emergency
        ("emergency stop everything", _r),
        ("kill all running sessions", _r),
        ("emergency kill switch", _r),
        ("stop everything now", _r),
        ("halt all agents", _r),
        ("panic stop", _r),
        # Approve
        ("approve the pending action", _r),
        ("reject that step", _r),
        ("what's waiting for approval", _r),
        ("are there any pending approvals", _r),
        ("approve it", _r),
        ("reject the step", _r),
        ("show pending approvals", _r),
    ]

    # ── SCHEDULE: create/list/update/delete schedules, triggers ──
    _s = "schedule"
    samples += [
        ("schedule my agent to run daily at 9am", _s),
        ("set up a schedule for every hour", _s),
        ("run this agent every Monday", _s),
        ("create a cron schedule", _s),
        ("set a trigger for my agent", _s),
        ("what schedules do I have", _s),
        ("list schedules for my agent", _s),
        ("delete the daily schedule", _s),
        ("disable the schedule", _s),
        ("update the schedule to run weekly", _s),
        ("change the schedule to 6am", _s),
        ("stop the recurring schedule", _s),
        ("I want it to run automatically every day", _s),
        ("set up automation for my agent", _s),
        ("how often does my agent run", _s),
        ("schedule it for every 6 hours", _s),
        ("create a daily schedule at midnight", _s),
        ("set up a weekly run on Fridays", _s),
        ("make it run every morning", _s),
        ("automate this agent", _s),
        ("set a recurring trigger", _s),
        ("configure the cron expression", _s),
        ("change schedule frequency", _s),
        ("pause the schedule", _s),
        ("resume the schedule", _s),
        ("remove the trigger", _s),
        ("cancel the automation", _s),
        ("create a webhook trigger", _s),
        ("set up a webhook for my agent", _s),
        ("fire the webhook", _s),
        ("list all triggers", _s),
        ("what triggers are active", _s),
        ("show me the schedule", _s),
        ("when does my agent run next", _s),
        ("update the cron to 0 */2 * * *", _s),
        ("schedule the scraper for hourly", _s),
        ("make it run twice a day", _s),
        ("set minutely schedule for testing", _s),
        ("remove all schedules", _s),
        ("delete the webhook trigger", _s),
    ]

    # ── INSPECT: view agents, sessions, steps, metrics, providers ──
    _i = "inspect"
    samples += [
        ("show me my agents", _i),
        ("list all agents", _i),
        ("how many agents do I have", _i),
        ("what agents exist in my workspace", _i),
        ("show agent details", _i),
        ("show me the session history", _i),
        ("what did my agent do in the last run", _i),
        ("show the execution steps", _i),
        ("show me the trace for that session", _i),
        ("what's the agent's performance", _i),
        ("show metrics for my scraper", _i),
        ("what was the success rate", _i),
        ("how many sessions has it run", _i),
        ("which providers are available", _i),
        ("what LLM models can I use", _i),
        ("is OpenAI working", _i),
        ("check provider status", _i),
        ("show me agent versions", _i),
        ("what's the agent's current config", _i),
        ("show me what happened", _i),
        ("inspect my agent", _i),
        ("tell me about this agent", _i),
        ("what tools does my agent have", _i),
        ("show the agent's tools", _i),
        ("what model is my agent using", _i),
        ("get agent info", _i),
        ("show agent snapshot", _i),
        ("describe this agent", _i),
        ("what's the status of my agents", _i),
        ("how is my agent performing", _i),
        ("show run details", _i),
        ("what steps did it take", _i),
        ("show session trace", _i),
        ("last run results", _i),
        ("how did the last execution go", _i),
        ("show me the run log", _i),
        ("agent performance metrics", _i),
        ("success rate of my agents", _i),
        ("platform metrics", _i),
        ("show overall stats", _i),
        ("watchdog status", _i),
        ("what capabilities does the platform have", _i),
        ("show me the limits", _i),
        ("check agent health", _i),
        ("how many runs today", _i),
        ("show execution history", _i),
        ("what providers are healthy", _i),
        ("agent version history", _i),
    ]

    # ── MEMORY: user/agent memory, RAG, insights ──
    _m = "memory"
    samples += [
        ("what do you remember about me", _m),
        ("save this preference", _m),
        ("remember that I prefer GPT-4o", _m),
        ("what has my agent learned", _m),
        ("show agent memory", _m),
        ("search memory for previous results", _m),
        ("what did we discuss last time", _m),
        ("recall previous agent configurations", _m),
        ("store this insight", _m),
        ("what patterns have you noticed", _m),
        ("what context do you have", _m),
        ("get your accumulated knowledge", _m),
        ("what do you know from past sessions", _m),
        ("remember this for next time", _m),
        ("store the fact that I like daily reports", _m),
        ("what do you know about my preferences", _m),
        ("show user memory", _m),
        ("get my stored preferences", _m),
        ("do you remember what we built last time", _m),
        ("recall my agent setup", _m),
        ("what insights have you stored", _m),
        ("show me your learnings", _m),
        ("retrieve your context", _m),
        ("what have you learned about me", _m),
        ("get agent memory for the scraper", _m),
        ("show dual memory for my research agent", _m),
        ("ask memory about previous configurations", _m),
        ("RAG search for agent patterns", _m),
        ("search your knowledge base", _m),
        ("what's in your memory about market research", _m),
        ("remember I want all agents to use groq", _m),
        ("save this preference: always use web_search", _m),
        ("note that I prefer low temperature", _m),
        ("what user preferences do you have", _m),
        ("agent knowledge graph", _m),
        ("collective knowledge for my agent", _m),
        ("what does my agent know", _m),
        ("show me what my agent has learned", _m),
        ("retrieve past insights", _m),
        ("get architect context", _m),
    ]

    # ── PLAN: TODO tasks, brainstorm, workspace plan ──
    _p = "plan"
    samples += [
        ("create a task to fix the scraper", _p),
        ("add a TODO item", _p),
        ("what's on my task list", _p),
        ("show me the plan", _p),
        ("update the task status to completed", _p),
        ("mark that task as done", _p),
        ("I have an idea for a new agent workflow", _p),
        ("brainstorm ways to improve my agents", _p),
        ("what's the workspace plan", _p),
        ("show all tasks across agents", _p),
        ("create a plan for building an agent pipeline", _p),
        ("list my pending tasks", _p),
        ("what's the priority of my tasks", _p),
        ("add a task: build scraper v2", _p),
        ("create TODO: integrate google calendar", _p),
        ("mark the scraper task as in progress", _p),
        ("update task priority to high", _p),
        ("what tasks are pending", _p),
        ("show blocked tasks", _p),
        ("list completed tasks", _p),
        ("brainstorm agent ideas for marketing", _p),
        ("I have an idea for a pipeline", _p),
        ("plan: first build scraper, then emailer", _p),
        ("show the full workspace plan", _p),
        ("what's the roadmap", _p),
        ("get all tasks and brainstorms", _p),
        ("any tasks for the research agent", _p),
        ("per-agent task list", _p),
        ("workspace TODO", _p),
        ("my ideas and plans", _p),
        ("delete that task", _p),
        ("remove the completed tasks", _p),
        ("update the brainstorm", _p),
        ("change task status", _p),
        ("high priority tasks only", _p),
        ("what are my next steps", _p),
        ("planning session", _p),
        ("let's plan the agent architecture", _p),
        ("help me plan my workflow", _p),
        ("organize my tasks", _p),
    ]

    # ── DELEGATE: multi-agent orchestration ──
    _d = "delegate"
    samples += [
        ("ask my research agent to find info about Tesla", _d),
        ("delegate this task to the scraper agent", _d),
        ("use my email agent to send the results", _d),
        ("have my writer agent create a blog post", _d),
        ("run the analysis agent on this data", _d),
        ("tell my monitor agent to check for changes", _d),
        ("chain these agents together", _d),
        ("use agent X to do Y", _d),
        ("delegate to the data agent", _d),
        ("ask another agent to handle this", _d),
        ("tell my scraper to fetch the latest data", _d),
        ("have the newsletter agent compile a report", _d),
        ("ask the research agent about competitors", _d),
        ("delegate research to the AI news agent", _d),
        ("use my crypto agent to check prices", _d),
        ("get my SEO agent to analyze this", _d),
        ("orchestrate a multi-agent workflow", _d),
        ("pipe output from scraper to emailer", _d),
        ("chain scraper → analyzer → emailer", _d),
        ("tell agent A to send results to agent B", _d),
        ("delegate to my market research agent", _d),
        ("ask the data agent to pull stats", _d),
        ("use my writer to draft a summary", _d),
        ("have the social agent post this", _d),
        ("delegate by name: Research Bot", _d),
        ("send this to my scraper", _d),
        ("let the analyzer process this", _d),
        ("forward to my email agent", _d),
        ("get my agent to do this task", _d),
        ("ask my Luna agent about events", _d),
        ("delegate the report to the writer agent", _d),
        ("can my monitor agent check this", _d),
        ("tell the scraper to run on this URL", _d),
        ("orchestrate agents for this goal", _d),
        ("multi-agent pipeline for research", _d),
        ("coordinate my agents on this project", _d),
        ("pass this to the next agent", _d),
        ("relay to my assistant agent", _d),
        ("sub-task to the helper agent", _d),
        ("hand off to the data collector", _d),
    ]

    # ── WORKSPACE: settings, credits, integrations, time, cleanup ──
    _w = "workspace"
    samples += [
        ("rename my workspace", _w),
        ("what's my credit balance", _w),
        ("how many credits do I have", _w),
        ("check my integrations", _w),
        ("is Google connected", _w),
        ("what's connected", _w),
        ("which OAuth services are linked", _w),
        ("what time is it", _w),
        ("show workspace databases", _w),
        ("what plan am I on", _w),
        ("check my billing", _w),
        ("clean up the workspace", _w),
        ("rename workspace to 'My Lab'", _w),
        ("set workspace icon", _w),
        ("change workspace name", _w),
        ("check credit balance", _w),
        ("do I have enough credits", _w),
        ("how much does it cost to run an agent", _w),
        ("credit check", _w),
        ("show my wallet", _w),
        ("what integrations are available", _w),
        ("connect google", _w),
        ("check if slack is connected", _w),
        ("which services need OAuth", _w),
        ("integration status", _w),
        ("is figma connected", _w),
        ("link my google account", _w),
        ("check connected services", _w),
        ("current time", _w),
        ("what timezone am I in", _w),
        ("show workspace info", _w),
        ("list databases", _w),
        ("per-agent databases", _w),
        ("show all workspace data", _w),
        ("workspace overview", _w),
        ("what's in my workspace", _w),
        ("workspace status", _w),
        ("billing info", _w),
        ("subscription details", _w),
        ("am I on the free plan", _w),
    ]

    # ── TEAMS: team management, members, workflows, NFTs, rentals ──
    _tm = "teams"
    samples += [
        ("create a new team", _tm),
        ("show me my teams", _tm),
        ("add a member to my team", _tm),
        ("list team members", _tm),
        ("delete the marketing team", _tm),
        ("update team settings", _tm),
        ("what team workflows are running", _tm),
        ("cancel the team workflow", _tm),
        ("archive the old team", _tm),
        ("restore the archived team", _tm),
        ("mint an NFT for my team", _tm),
        ("rent access to this team", _tm),
        ("transfer team ownership", _tm),
        ("check team rental status", _tm),
        ("show my rentals", _tm),
        ("create team called Research Squad", _tm),
        ("list all teams", _tm),
        ("who's in my team", _tm),
        ("team details", _tm),
        ("update the team description", _tm),
        ("rename the team", _tm),
        ("remove member from team", _tm),
        ("team workflow status", _tm),
        ("stop the team workflow", _tm),
        ("archive this team", _tm),
        ("unarchive the research team", _tm),
        ("mint NFT", _tm),
        ("rent this team's agents", _tm),
        ("transfer team to another user", _tm),
        ("my team rentals", _tm),
        ("team ownership info", _tm),
        ("how many teams do I have", _tm),
        ("manage my teams", _tm),
        ("team members and roles", _tm),
        ("create a team for marketing", _tm),
        ("delete the old team", _tm),
        ("show team workflows", _tm),
        ("team NFT status", _tm),
        ("rent pricing for my team", _tm),
        ("team collaboration settings", _tm),
    ]

    # ── MARKETPLACE: publish, list, APIs ──
    _mk = "marketplace"
    samples += [
        ("publish my agent to the marketplace", _mk),
        ("list marketplace agents", _mk),
        ("remove my agent from marketplace", _mk),
        ("how much should I charge for my agent", _mk),
        ("publish my agent as an API", _mk),
        ("unpublish the agent API", _mk),
        ("show published APIs for my agent", _mk),
        ("delete the published API", _mk),
        ("call a public agent API", _mk),
        ("show marketplace listings", _mk),
        ("I want to sell my agent", _mk),
        ("make my agent available to others", _mk),
        ("publish agent to marketplace", _mk),
        ("marketplace listing price", _mk),
        ("unlist from marketplace", _mk),
        ("create a public API for my agent", _mk),
        ("make agent API public", _mk),
        ("API slug for my agent", _mk),
        ("show my published agents", _mk),
        ("browse marketplace", _mk),
        ("find agents on marketplace", _mk),
        ("marketplace search", _mk),
        ("who's using my published agent", _mk),
        ("agent API usage stats", _mk),
        ("call the public weather agent API", _mk),
        ("invoke published agent endpoint", _mk),
        ("set marketplace price to $5", _mk),
        ("monetize my agent", _mk),
        ("list my published APIs", _mk),
        ("remove from marketplace listing", _mk),
        ("agent store", _mk),
        ("sell my agent for credits", _mk),
        ("publish and set pricing", _mk),
        ("public API documentation", _mk),
        ("marketplace analytics", _mk),
        ("how many people installed my agent", _mk),
        ("unpublish from store", _mk),
        ("marketplace revenue", _mk),
        ("public agent directory", _mk),
        ("agent marketplace stats", _mk),
    ]

    # ── FEDERATION: cross-node agents ──
    _fd = "federation"
    samples += [
        ("show federated agents", _fd),
        ("register for federation", _fd),
        ("connect to another node", _fd),
        ("disconnect federated agent", _fd),
        ("check federation status", _fd),
        ("send federation heartbeat", _fd),
        ("poll for federation tasks", _fd),
        ("submit federation result", _fd),
        ("list agents from other nodes", _fd),
        ("federate my agent", _fd),
        ("cross-node agent sharing", _fd),
        ("federation node registration", _fd),
        ("heartbeat to federation network", _fd),
        ("federated task polling", _fd),
        ("submit step result to federation", _fd),
        ("disconnect from federation", _fd),
        ("federation capabilities", _fd),
        ("register this node", _fd),
        ("other nodes' agents", _fd),
        ("federation network status", _fd),
        ("list federated nodes", _fd),
        ("cross-node task submission", _fd),
        ("federation peer discovery", _fd),
        ("remote agent execution", _fd),
        ("inter-node communication", _fd),
        ("federation architecture", _fd),
        ("distributed agent network", _fd),
        ("node-to-node federation", _fd),
        ("federation protocol status", _fd),
        ("decentralized agent mesh", _fd),
        ("register federation node URL", _fd),
        ("poll available remote tasks", _fd),
        ("submit federated result", _fd),
        ("check federated agent health", _fd),
        ("cross-platform agent sharing", _fd),
        ("external node connection", _fd),
        ("federation connectivity", _fd),
        ("remote node agents", _fd),
        ("list distributed agents", _fd),
        ("federation dashboard", _fd),
    ]

    # ── GOVERNANCE: compliance, audit ──
    _gv = "governance"
    samples += [
        ("check compliance score", _gv),
        ("show the audit trail", _gv),
        ("generate compliance report", _gv),
        ("evaluate governance for this action", _gv),
        ("export audit data", _gv),
        ("show evidence checklist", _gv),
        ("is this action compliant", _gv),
        ("what's our compliance status", _gv),
        ("review governance policies", _gv),
        ("audit log for my agents", _gv),
        ("compliance evidence", _gv),
        ("governance evaluation", _gv),
        ("audit trail export", _gv),
        ("compliance checklist", _gv),
        ("governance policies review", _gv),
        ("is this permitted by governance", _gv),
        ("check if action is allowed", _gv),
        ("compliance reporting", _gv),
        ("governance audit", _gv),
        ("show compliance metrics", _gv),
        ("what's the compliance score", _gv),
        ("export governance data", _gv),
        ("audit history", _gv),
        ("policy evaluation", _gv),
        ("governance dashboard", _gv),
        ("compliance status report", _gv),
        ("evidence collection for audit", _gv),
        ("regulatory compliance", _gv),
        ("data governance check", _gv),
        ("compliance evidence checklist", _gv),
        ("show audit records", _gv),
        ("governance policy violations", _gv),
        ("compliance assessment", _gv),
        ("audit data for last month", _gv),
        ("governance framework status", _gv),
        ("is my workspace compliant", _gv),
        ("show governance actions", _gv),
        ("compliance certification", _gv),
        ("audit report generation", _gv),
        ("governance overview", _gv),
    ]

    # ── LEARNING: patterns, recommendations, feedback ──
    _ln = "learning"
    samples += [
        ("what patterns have my agents learned", _ln),
        ("get recommendations for my agent", _ln),
        ("show learning statistics", _ln),
        ("what has the system learned", _ln),
        ("give feedback on that session", _ln),
        ("rate the last run", _ln),
        ("how can I improve my agent", _ln),
        ("show classifier stats", _ln),
        ("retrain the tool classifier", _ln),
        ("what knowledge has my agent accumulated", _ln),
        ("suggest improvements for my agents", _ln),
        ("learning patterns analysis", _ln),
        ("agent performance recommendations", _ln),
        ("submit feedback for session", _ln),
        ("rate this execution 4 stars", _ln),
        ("session feedback: good results", _ln),
        ("improvement suggestions", _ln),
        ("classifier accuracy", _ln),
        ("retrain the model", _ln),
        ("add custom training data", _ln),
        ("learning system overview", _ln),
        ("accumulated agent knowledge", _ln),
        ("what has the AI learned", _ln),
        ("show me optimization suggestions", _ln),
        ("agent improvement recommendations", _ln),
        ("learning history", _ln),
        ("classifier training stats", _ln),
        ("neural classifier performance", _ln),
        ("how to improve agent success rate", _ln),
        ("what changes would help my agent", _ln),
        ("feedback on the last run: it was slow", _ln),
        ("rate session: 3 out of 5", _ln),
        ("learning insights", _ln),
        ("pattern detection for agents", _ln),
        ("recommendation engine results", _ln),
        ("add custom tools to classifier", _ln),
        ("classifier retraining needed", _ln),
        ("agent knowledge base", _ln),
        ("what did my agent learn from its runs", _ln),
        ("collective intelligence report", _ln),
    ]

    # ── ADVANCED: anomaly, templates, limits, direct execution ──
    _ad = "advanced"
    samples += [
        ("set up anomaly detection", _ad),
        ("create an anomaly trigger", _ad),
        ("list anomaly triggers", _ad),
        ("delete the anomaly trigger", _ad),
        ("fire the anomaly trigger for testing", _ad),
        ("show available templates", _ad),
        ("create agent from template", _ad),
        ("what are the platform limits", _ad),
        ("update the rate limit", _ad),
        ("execute this tool directly", _ad),
        ("test the web_search tool", _ad),
        ("get the async tool result", _ad),
        ("anomaly detection for my agent", _ad),
        ("configure anomaly threshold", _ad),
        ("anomaly alert on failure rate", _ad),
        ("template gallery", _ad),
        ("instantiate the scraper template", _ad),
        ("use a template to build quickly", _ad),
        ("platform rate limits", _ad),
        ("change the limit for API calls", _ad),
        ("test tool: fetch_url", _ad),
        ("directly execute web_search", _ad),
        ("tool execution result", _ad),
        ("get task result by ID", _ad),
        ("predict optimal tools for this goal", _ad),
        ("neural tool prediction", _ad),
        ("anomaly monitoring", _ad),
        ("alert when agent fails 3 times", _ad),
        ("anomaly trigger configuration", _ad),
        ("delete anomaly alert", _ad),
        ("fire test anomaly", _ad),
        ("browse templates", _ad),
        ("create from template: newsletter bot", _ad),
        ("what templates exist", _ad),
        ("current rate limits", _ad),
        ("increase API limit", _ad),
        ("tool testing sandbox", _ad),
        ("execute tool for verification", _ad),
        ("async result polling", _ad),
        ("direct tool test", _ad),
    ]

    # ── GENERAL CHAT (no tools needed) ──
    _n = "none"
    samples += [
        ("hello", _n),
        ("hi there", _n),
        ("thanks", _n),
        ("what can you do", _n),
        ("how does this work", _n),
        ("explain agents to me", _n),
        ("what is an AI agent", _n),
        ("goodbye", _n),
        ("ok", _n),
        ("sure", _n),
        ("that's cool", _n),
        ("interesting", _n),
        ("tell me more", _n),
        ("I don't understand", _n),
        ("help", _n),
        ("hey", _n),
        ("good morning", _n),
        ("thank you so much", _n),
        ("nice work", _n),
        ("great job", _n),
        ("what are you", _n),
        ("who made you", _n),
        ("are you an AI", _n),
        ("how do agents work", _n),
        ("explain how this platform works", _n),
        ("what's this for", _n),
        ("I'm new here", _n),
        ("how do I get started", _n),
        ("what's the difference between agents and bots", _n),
        ("that makes sense", _n),
        ("got it", _n),
        ("understood", _n),
        ("no thanks", _n),
        ("nevermind", _n),
        ("never mind", _n),
        ("sorry", _n),
        ("my bad", _n),
        ("I see", _n),
        ("cool", _n),
        ("awesome", _n),
        ("what else can you do", _n),
        ("tell me about yourself", _n),
        ("how are you", _n),
        ("lol", _n),
        ("haha", _n),
    ]

    return samples
