"""Tool Models — 161 platform tools + 101 Agent Engine API endpoints"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class ToolCategory(str, Enum):
    BUILTIN = "builtin"
    OAUTH = "oauth"
    CUSTOM = "custom"
    SCRAPER = "scraper"


@dataclass
class ToolDefinition:
    name: str
    description: str
    category: ToolCategory
    parameters: Dict[str, Any] = field(default_factory=dict)
    oauth_service: Optional[str] = None
    scopes: List[str] = field(default_factory=list)


BUILTIN_TOOLS = [
    "web_search", "scrape_page", "deep_research", "stock_market_data",
    "send_email", "configure_smtp", "delete_smtp", "build_chart",
    "scrape_platforms", "google_sheets", "create_presentation",
    "documents", "generate_media",
]

OAUTH_SERVICES = [
    "airtable", "asana", "atlassian", "attio", "calendly", "clickup",
    "discord", "dribbble", "dropbox", "figma", "github", "gitlab",
    "gmail", "google_calendar", "google_docs", "google_drive", "hubspot",
    "linear", "linkedin", "mailchimp", "microsoft", "miro", "monday",
    "notion", "pipedrive", "salesforce", "slack", "typeform", "x_twitter",
    "xero", "youtube", "zoho_crm", "zoom",
]

def _t(name, desc, props=None, required=None):
    schema = {"type": "object", "properties": props or {}, "required": required or []}
    return {"type": "function", "function": {"name": name, "description": desc, "parameters": schema}}

ORCHESTRATOR_TOOLS = [
    _t("workspace_snapshot", "Get all agents and workspace state"),
    _t("list_workspace_tools", "List available tools for agents"),
    _t("get_user_memory", "Get stored user preferences"),
    _t("update_user_memory", "Store a user fact",
       {"content": {"type": "string"}}, ["content"]),
    _t("agent_snapshot", "Get agent details and recent runs",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("run_snapshot", "Get run details",
       {"run_id": {"type": "string"}}, ["run_id"]),
    _t("declare_multi_agent_plan",
       "Call this FIRST, before build_agent, ONLY when the user's request needs a coordinated TEAM of agents with distinct roles (e.g. a podcast pipeline: script agent + image agent + voice agent) — not for an ordinary single-agent request. Declaring a plan lets you call build_agent multiple times in this turn, followed by create_team.",
       {"team_name": {"type": "string", "description": "Name for the team"},
        "agents": {"type": "array", "items": {"type": "object"}, "description": "List of {name, role} for each agent you're about to build"}},
       ["team_name", "agents"]),
    _t("build_agent", "Create a new autonomous agent with proper configuration",
       {"name": {"type": "string", "description": "Agent name"},
        "goal": {"type": "string", "description": "What the agent should do — outcome-oriented, no recurrence language"},
        "icon": {"type": "string", "description": "Emoji icon"},
        "tools": {"type": "array", "items": {"type": "string"}, "description": "List of tools the agent needs (e.g. web_search, fetch_url, scrape_page, memory_write)"},
        "max_loops": {"type": "integer", "description": "Max execution loops — estimate based on task complexity (20-50)"},
        "model": {"type": "string", "description": "LLM model (groq/llama-3.3-70b-versatile, openai/gpt-4o, anthropic/claude-sonnet-4-6) — leave unset to let the platform pick a verified-working one"},
        "temperature": {"type": "number", "description": "Temperature (0.3-0.8 based on creativity needed)"}}, ["name", "goal"]),
    _t("continue_build", "Update agent instructions",
       {"agent_id": {"type": "string"}, "instructions": {"type": "string"}}, ["agent_id", "instructions"]),
    _t("message_build", "Refine agent via natural language",
       {"agent_id": {"type": "string"}, "message": {"type": "string"}}, ["agent_id", "message"]),
    _t("run_agent", "Execute an agent now",
       {"agent_id": {"type": "string"}, "goal": {"type": "string", "description": "Optional goal override"}}, ["agent_id"]),
    _t("stop_run", "Stop an active run",
       {"run_id": {"type": "string"}}, ["run_id"]),
    _t("delete_agent", "Permanently delete a single agent by ID",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("delete_all_agents", "Delete ALL agents in the workspace. Use when user wants to delete all/multiple agents at once."),
    _t("modify_agent", "Add or remove tools, update config on an existing agent",
       {"agent_id": {"type": "string", "description": "Agent ID to modify"},
        "add_tools": {"type": "string", "description": "Comma-separated tools to add"},
        "remove_tools": {"type": "string", "description": "Comma-separated tools to remove"},
        "max_loops": {"type": "integer", "description": "New max loops value"},
        "temperature": {"type": "number", "description": "New temperature"},
        "model": {"type": "string", "description": "New model"}}, ["agent_id"]),
    _t("set_trigger", "Schedule agent to run on interval (minutely, hourly, daily, weekly)",
       {"agent_id": {"type": "string"}, "interval": {"type": "string", "description": "One of: minutely, hourly, daily, weekly"},
        "timezone": {"type": "string"}}, ["agent_id", "interval"]),
    _t("set_workspace_name", "Rename workspace",
       {"name": {"type": "string"}, "icon": {"type": "string"}}, ["name"]),
    _t("present_options", "Show user a choice between 2-4 options",
       {"question": {"type": "string"}, "options": {"type": "string", "description": "Comma-separated list of options"}}, ["question", "options"]),
    _t("get_current_time", "Get current UTC time"),
    _t("list_workspace_databases", "List per-agent databases"),
    _t("get_credits_info", "Get user wallet, credits, plan, and economic state"),
    _t("check_credits", "Check if user has enough credits to run an agent"),
    _t("check_integrations", "Check which OAuth integrations are connected and which are missing",
       {"tools": {"type": "string", "description": "Comma-separated tool names that need integrations"}}, ["tools"]),
    _t("get_agent_settings", "Get agent-specific settings from auth service",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("get_agent_chain_status", "Get agent blockchain registration and identity status",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("get_agent_memory", "Get agent-specific hash sphere memory and learnings",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("get_dual_memory", "Get combined user + agent hash sphere memory",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("ask_memory", "Ask a question to RAG memory — agent learns from past context",
       {"question": {"type": "string"}, "agent_id": {"type": "string"}}, ["question"]),
    _t("store_insight", "Store something you learned during this conversation for future reference",
       {"insight": {"type": "string", "description": "What you learned"}, "category": {"type": "string", "description": "One of: observation, user_preference, agent_pattern, failure_pattern, success_pattern"}},
       ["insight", "category"]),
    _t("retrieve_architect_context", "Get your accumulated knowledge: past insights, user preferences, patterns you've noticed. Call this at the start of every session to remember what you know."),
    # ── Prompt Management ──
    _t("get_agent_prompt", "Read an agent's current system prompt / instructions",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("update_agent_prompt", "Write or replace an agent's system prompt / instructions",
       {"agent_id": {"type": "string"}, "prompt": {"type": "string", "description": "The full new system prompt text"}},
       ["agent_id", "prompt"]),
    # ── Agent Config ──
    _t("update_agent_config", "Update agent configuration: model, temperature, max_tokens, mode, tools, provider, is_active, max_loops, tool_mode",
       {"agent_id": {"type": "string"},
        "model": {"type": "string", "description": "LLM model e.g. groq/llama-3.3-70b-versatile, openai/gpt-4o"},
        "temperature": {"type": "number"}, "max_tokens": {"type": "integer"},
        "mode": {"type": "string", "description": "Agent mode: smart, autonomous, manual"},
        "tools": {"type": "array", "items": {"type": "string"}, "description": "Replace tool list"},
        "is_active": {"type": "boolean"}, "max_loops": {"type": "integer"},
        "tool_mode": {"type": "string", "description": "smart or manual"}}, ["agent_id"]),
    # ── Schedules ──
    _t("create_schedule", "Create a cron schedule for an agent to run automatically",
       {"agent_id": {"type": "string"},
        "cron": {"type": "string", "description": "Cron expression e.g. '0 9 * * *' for daily 9am, '0 * * * *' for hourly"},
        "goal": {"type": "string", "description": "Goal override for scheduled runs"},
        "timezone": {"type": "string", "description": "Timezone e.g. UTC, America/New_York"}}, ["agent_id", "cron"]),
    # ── Session History ──
    _t("get_agent_sessions", "Get recent execution sessions/runs for an agent",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("get_session_steps", "Get step-by-step execution trace for a specific session/run",
       {"session_id": {"type": "string"}}, ["session_id"]),
    # ── Agent Delegation (spawn / use any agent) ──
    _t("delegate_to_agent", "Delegate a sub-task to any existing agent by ID — agent runs and returns its result. Use this to orchestrate multi-agent workflows.",
       {"agent_id": {"type": "string", "description": "ID of the agent to delegate to"},
        "task": {"type": "string", "description": "The task/goal for the agent to execute"}}, ["agent_id", "task"]),
    _t("delegate_by_name", "Delegate a sub-task to an agent by NAME — finds the agent and runs it. Use when user says 'ask my X agent to do Y'.",
       {"agent_name": {"type": "string", "description": "Name of the agent to delegate to"},
        "task": {"type": "string", "description": "The task/goal for the agent to execute"}}, ["agent_name", "task"]),
    # ── TODO / Planning / Brainstorm ──
    _t("create_task", "Create a TODO task — persisted in workspace memory. Can be per-agent or workspace-wide.",
       {"title": {"type": "string", "description": "Task title"},
        "description": {"type": "string", "description": "Detailed description"},
        "priority": {"type": "string", "description": "One of: high, medium, low"},
        "status": {"type": "string", "description": "One of: pending, in_progress, completed, blocked"},
        "agent_id": {"type": "string", "description": "Optional — scope task to a specific agent"},
        "tags": {"type": "string", "description": "Comma-separated tags"}}, ["title"]),
    _t("list_tasks", "List TODO tasks from workspace memory. Filter by agent_id for per-agent tasks, or leave empty for all workspace tasks.",
       {"agent_id": {"type": "string", "description": "Optional — filter tasks for specific agent"},
        "query": {"type": "string", "description": "Optional search query to filter tasks"}}, []),
    _t("update_task", "Update a task's status, priority, or description.",
       {"task_id": {"type": "string", "description": "Task ID to update"},
        "status": {"type": "string", "description": "New status: pending, in_progress, completed, blocked"},
        "priority": {"type": "string", "description": "New priority: high, medium, low"},
        "title": {"type": "string", "description": "Updated title"},
        "description": {"type": "string", "description": "Updated description"},
        "agent_id": {"type": "string", "description": "Agent scope"}}, ["task_id"]),
    _t("brainstorm", "Store a brainstorm idea or plan — persisted in workspace memory. Can be per-agent or general.",
       {"content": {"type": "string", "description": "The brainstorm idea, plan, or thought"},
        "agent_id": {"type": "string", "description": "Optional — scope to a specific agent"}}, ["content"]),
    _t("get_workspace_plan", "Get the full workspace plan: all TODO tasks + brainstorms across all agents. Use this to review the current state of planning."),
    # ── Session Control (cancel, approve, emergency stop) ──
    _t("cancel_session", "Cancel/stop a running agent session immediately.",
       {"session_id": {"type": "string", "description": "Session ID to cancel"}}, ["session_id"]),
    _t("emergency_stop", "EMERGENCY KILL SWITCH — cancel ALL running sessions and disable ALL schedules for an agent. Use when agent is out of control.",
       {"agent_id": {"type": "string", "description": "Agent ID to emergency stop"}}, ["agent_id"]),
    _t("approve_step", "Approve a pending step that requires human approval.",
       {"session_id": {"type": "string", "description": "Session ID"},
        "step_id": {"type": "string", "description": "Step ID to approve"}}, ["session_id", "step_id"]),
    _t("get_pending_approvals", "List all pending approval requests across all agents."),
    # ── Full Tool Registry (161 tools from Agent Engine) ──
    _t("list_engine_tools", "List ALL 161 platform tools from Agent Engine. See every tool available for agents."),
    _t("execute_tool", "Execute any platform tool directly for testing. Verify a tool works before assigning it to an agent.",
       {"tool_name": {"type": "string", "description": "Tool name (e.g. web_search, fetch_url)"},
        "tool_input": {"type": "object", "description": "Input parameters for the tool"}}, ["tool_name", "tool_input"]),
    _t("predict_tools", "Use neural classifier to predict optimal tools for a goal. Returns ranked tool list from 161 tools.",
       {"goal": {"type": "string", "description": "The agent's goal text"},
        "n": {"type": "integer", "description": "Number of tools to return (default 10)"}}, ["goal"]),
    _t("retrain_tool_classifier", "Retrain the neural tool classifier with new data.",
       {"custom_samples": {"type": "array", "description": "Optional [[message, context, tool_id], ...] training samples"}}, []),
    _t("get_tool_classifier_stats", "Get neural tool classifier statistics — accuracy, sample count, etc."),
    _t("add_custom_tools", "Add custom tool labels to the classifier for new tools.",
       {"tools": {"type": "array", "description": "List of tool definitions to add"}}, ["tools"]),
    _t("get_tool_result", "Get async tool execution result by task ID.",
       {"task_id": {"type": "string"}}, ["task_id"]),
    # ── Provider & Metrics ──
    _t("list_providers", "List all available LLM providers and models. Check which are healthy before selecting a model."),
    _t("check_llm_status", "Check which LLM providers are actually live and usable — tests system keys and shows user BYOK keys. Use this before recommending a model."),
    _t("get_agent_metrics", "Get performance metrics for an agent: sessions, success rate, avg duration.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("get_platform_metrics", "Get overall platform metrics — total agents, sessions, success rates."),
    _t("get_metrics_summary", "Get condensed platform metrics summary."),
    # ── Schedule Management ──
    _t("list_schedules", "List all cron schedules for an agent.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("update_schedule", "Update an existing schedule's cron expression or config.",
       {"schedule_id": {"type": "string"}, "cron": {"type": "string"},
        "goal": {"type": "string"}, "timezone": {"type": "string"}}, ["schedule_id"]),
    _t("delete_schedule", "Delete a schedule by ID.",
       {"schedule_id": {"type": "string"}}, ["schedule_id"]),
    # ── Triggers & Webhooks ──
    _t("create_trigger", "Create a webhook trigger for an agent.",
       {"agent_id": {"type": "string"}, "trigger_type": {"type": "string"},
        "config": {"type": "object"}}, ["agent_id"]),
    _t("list_triggers", "List all triggers for an agent.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("fire_webhook_trigger", "Fire a webhook trigger to start an agent.",
       {"trigger_id": {"type": "string"}, "payload": {"type": "object"}}, ["trigger_id"]),
    # ── Anomaly Detection ──
    _t("list_anomaly_triggers", "List all anomaly detection triggers."),
    _t("create_anomaly_trigger", "Create an anomaly detection trigger.",
       {"agent_id": {"type": "string"}, "metric": {"type": "string"},
        "threshold": {"type": "number"}, "action": {"type": "string"}}, ["agent_id", "metric"]),
    _t("delete_anomaly_trigger", "Delete an anomaly trigger.",
       {"trigger_id": {"type": "string"}}, ["trigger_id"]),
    _t("fire_anomaly_trigger", "Manually fire an anomaly trigger for testing.",
       {"trigger_id": {"type": "string"}}, []),
    # ── Session Deep Inspection ──
    _t("get_session_detail", "Get full session details including metadata.",
       {"session_id": {"type": "string"}}, ["session_id"]),
    _t("get_session_trace", "Get full execution trace with timing for a session.",
       {"session_id": {"type": "string"}}, ["session_id"]),
    _t("submit_session_feedback", "Submit feedback for a session (rating, notes).",
       {"session_id": {"type": "string"}, "rating": {"type": "integer"},
        "feedback": {"type": "string"}}, ["session_id"]),
    _t("stream_session_sse", "Connect to live SSE stream for a running session.",
       {"session_id": {"type": "string"}}, ["session_id"]),
    # ── Agent Versions ──
    _t("get_agent_versions", "Get version history for an agent.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    # ── Agent Mode ──
    _t("set_agent_mode", "Change agent mode: smart, autonomous, manual.",
       {"agent_id": {"type": "string"}, "mode": {"type": "string"}}, ["agent_id", "mode"]),
    _t("unarchive_agent", "Restore an archived agent.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    # ── Templates ──
    _t("list_templates", "List all available agent templates."),
    _t("instantiate_template", "Create a new agent from a template.",
       {"template_id": {"type": "string"}, "name": {"type": "string"},
        "goal": {"type": "string"}}, ["template_id"]),
    # ── Federation ──
    _t("list_federated_agents", "List agents federated from other nodes."),
    _t("register_federation", "Register this node for federation.",
       {"node_url": {"type": "string"}, "capabilities": {"type": "array"}}, ["node_url"]),
    _t("federation_heartbeat", "Send federation heartbeat.",
       {"node_id": {"type": "string"}}, ["node_id"]),
    _t("disconnect_federation", "Disconnect a federated agent.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("submit_federation_step", "Submit a step result for a federated task.",
       {"task_id": {"type": "string"}, "step_data": {"type": "object"}}, ["task_id"]),
    _t("submit_federation_result", "Submit final result for a federated task.",
       {"task_id": {"type": "string"}, "result": {"type": "object"}}, ["task_id"]),
    _t("poll_federation_tasks", "Poll for available federation tasks."),
    # ── Governance & Compliance ──
    _t("evaluate_governance", "Evaluate an action against governance policies.",
       {"action": {"type": "string"}, "context": {"type": "object"}}, ["action"]),
    _t("get_governance_audit_trail", "Get the full governance audit trail."),
    _t("get_compliance_report", "Get comprehensive compliance report."),
    _t("get_compliance_score", "Get current compliance score."),
    _t("get_compliance_evidence", "Get evidence checklist for compliance."),
    _t("export_compliance_audit", "Export compliance audit data."),
    # ── Teams & Collaboration ──
    _t("list_teams", "List all teams."),
    _t("create_team", "Create a new team.",
       {"name": {"type": "string"}, "description": {"type": "string"}}, ["name"]),
    _t("get_team", "Get team details.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("update_team", "Update team config.",
       {"team_id": {"type": "string"}, "name": {"type": "string"},
        "description": {"type": "string"}}, ["team_id"]),
    _t("delete_team", "Delete a team.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("get_team_members", "Get team members.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("get_team_ownership", "Get team ownership info.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("get_team_workflows", "Get team workflows.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("cancel_team_workflow", "Cancel a running team workflow.",
       {"workflow_id": {"type": "string"}}, ["workflow_id"]),
    _t("archive_team", "Archive a team.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("unarchive_team", "Restore an archived team.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("mint_team_nft", "Mint an NFT for a team.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("rent_team", "Rent access to a team.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("transfer_team", "Transfer team ownership.",
       {"team_id": {"type": "string"}, "new_owner": {"type": "string"}}, ["team_id", "new_owner"]),
    _t("get_team_rentals", "Get team rental info.",
       {"team_id": {"type": "string"}}, ["team_id"]),
    _t("get_my_rentals", "Get my rental info across all teams."),
    # ── Marketplace & Publishing ──
    _t("get_marketplace", "Get marketplace listings."),
    _t("publish_agent", "Publish agent to the platform.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("marketplace_publish", "Publish agent to marketplace.",
       {"agent_id": {"type": "string"}, "price": {"type": "number"},
        "description": {"type": "string"}}, ["agent_id"]),
    _t("marketplace_unpublish", "Remove agent from marketplace.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("publish_agent_api", "Publish agent as a callable API.",
       {"agent_id": {"type": "string"}, "slug": {"type": "string"}}, ["agent_id"]),
    _t("unpublish_agent_api", "Unpublish an agent's API.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("get_published_apis", "Get published APIs for an agent.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("delete_published_api", "Delete a published API.",
       {"pub_id": {"type": "string"}}, ["pub_id"]),
    _t("call_public_api", "Call a published agent API by slug.",
       {"slug": {"type": "string"}, "input": {"type": "object"}}, ["slug"]),
    # ── Learning & Recommendations ──
    _t("get_learning_patterns", "Get learned patterns from agent executions."),
    _t("get_learning_recommendations", "Get AI recommendations for improving an agent.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    _t("get_learning_stats", "Get learning system statistics."),
    _t("get_agent_knowledge", "Get collective knowledge accumulated by an agent.",
       {"agent_id": {"type": "string"}}, ["agent_id"]),
    # ── Limits & Capabilities ──
    _t("get_limits", "Get platform rate limits and usage limits."),
    _t("update_limit", "Update a specific limit.",
       {"limit_id": {"type": "string"}, "value": {"type": "integer"}}, ["limit_id"]),
    _t("get_capabilities", "Get platform capabilities and feature flags."),
    # ── Watchdog ──
    _t("get_watchdog_status", "Get watchdog health monitoring status."),
    # ── Repo to Agent ──
    _t("repo_to_agent", "Convert a GitHub repository into an agent.",
       {"repo_url": {"type": "string"}, "name": {"type": "string"}}, ["repo_url"]),
    _t("analyze_repo", "Analyze a GitHub repository before converting to agent.",
       {"repo_url": {"type": "string"}}, ["repo_url"]),
    # ── Available Tools for Agents ──
    _t("get_available_tools", "Get list of tools available for agent assignment."),
]
